version: "3.9"
services:
  postgres:
    image: postgres
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  todo-list:
    build: "."
    depends_on:
      - postgres
    ports:
      - 5000:5000
    environment:
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
